# Generated by Django 2.2.3 on 2019-07-31 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190726_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverauthentication',
            name='redirect_uri',
            field=models.URLField(default='http://google.com'),
            preserve_default=False,
        ),
    ]
